# Generated by Django 4.1.5 on 2023-07-11 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_csvrow_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvrow',
            name='people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.person'),
        ),
    ]
