# Generated by Django 4.2 on 2023-07-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_take_course_remove_take_student_and_more'),
        ('api', '0003_alter_csvrow_people'),
    ]

    operations = [
    ]
