# Generated by Django 4.2.2 on 2023-07-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20230714_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvrow',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
