# Generated by Django 4.2.2 on 2023-07-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20230714_1416'),
        ('api', '0005_alter_csvrow_people_alter_person_comments'),
        ('api', '0005_alter_person_comments'),
    ]

    operations = [
    ]
