# Generated by Django 4.2.2 on 2023-07-17 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20230717_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvrow',
            name='people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.person'),
        ),
    ]
